---
title: Мазлумян
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: redcarpet
pygments: false
permalink: "/text/:title"
tagline: Текстохранилище
description: Текстохранилище
url: http://mazlumyan.github.io
author:
  name: Мазлумян
  url: https://vk.com/mzlmn
paginate: 8
icon: "/assets/images/teschalogo.png"
cover: "/assets/images/skycover3.jpg"
social:
- icon: vk
  url: https://vk.com/mzlmn
  desc: Вконтакте
- icon: instagram
  url: http://instagram.com/mazlumyanartyom/
  desc: Инстаграм
- icon: twitter
  url: https://twitter.com/tema_mazlumyan
  desc: Твиттер
- icon: rss
  url: http://mzlmn.github.io/atom.xml
  desc: Subscribe to my feed
menu:
- title: В самое начало
  url: "/"
- title: Здесь ничего нет
  url: "/404.html"
copyright:
  author: Мазлумян
  url: http://mzlmn.github.io
  type_title: Все тексты сам писал, отвечаю.
  type_url: http://creativecommons.org/licenses/by-nc/2.5
